### ISSUE TITLE
Operator alias for 'current-point' is missing

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Content-raku#26]
I cannot find an op code representing the method 'current-point' as is defined in PostScript. It would be convenient to have one so the user could easily determine if the current point is defined and use it or change it if desired. For example, my naive use of 'cp' as an alias:

    method cp {
        .current-point
    }
    ...

    my $g = $page.gfx;
    if $g.cp.head.defined {
        say "current point is: {$g.cp.head}, {$g.cp.tail}";
        # it's as is expected, continue to add to the current path
        my $point = $g.LineTo: $x, $y;
    } 
    else {
        # begin a new path
        my $point = $g.MoveTo: $x, $y;
    }

**Comment by dwarring** [comment]
I've changed just changed `current-point()` to return an undefined List rather than `(undef, undef)`, I think this better matches the PDF 1.7 and 2.0 specs which describes current point as `undefined`.

Hopefully, it also helps in your case. This simple test now works: `if $g.current-point {...}`

Released with PDF::Content 0.8.12

**Comment by tbrowder** [comment]
Thanks, David!
